language: node_js
node_js:
  - "0.10"
before_script:
  - "npm install -g grunt-cli"
  - "grunt coffee:clean coffee"
  - "git config --global user.email 'you@example.com'"
  - "git config --global user.name 'Your Name'"